server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html/browser;
    index index.html;
    include /etc/nginx/mime.types;
    types {
        application/wasm wasm;
    }

    location = /acoi {
        return 301 /acoi/;
    }

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://acoi_node_backend:8089/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~* \.(?:css|js|woff2?|eot|ttf|otf|wasm)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location ~* \.(?:png|jpg|jpeg|gif|svg|ico)$ {
        expires 30d;
        access_log off;
    }

    error_page 404 /index.html;
}
