services:
  database:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup.sql:/backup.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - internal_network
    entrypoint: ["/bin/sh", "-c", "docker-entrypoint.sh mysqld & sleep 20 && mysql -uroot -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < /backup.sql && wait"]

  backend:
    build:
      context: ./Web Application/backend
    container_name: node_backend
    restart: always
    environment:
      - PORT=8088
      - DB_HOST=database
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DOCKER_ENV=true
    ports:
      - "8088:8088"
    volumes:
      - ./Web Application/backend:/app
    working_dir: /app
    command: ["node", "server.js"]
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal_network
      - public_network

  frontend:
    build:
      context: ./Web Application/angular-frontend
    ports:
      - "8089:80"
    depends_on:
      - backend
    networks:
      - public_network

volumes:
  mysql_data:

networks:
  internal_network:
    internal: true
  public_network:
