version: "3.9"

services:
  database:
    image: mysql:8
    container_name: acoi_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - acoi_mysql_data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 5s
    networks:
      - internal_network

  backend:
    build:
      context: ./app/backend
    container_name: acoi_node_backend
    restart: always
    environment:
      - PORT=8089
      - DB_HOST=database
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DOCKER_ENV=true
    ports:
      - "8089:8089"
    volumes:
      - ./app/backend:/app
    working_dir: /app
    command: ["node", "server.js"]
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal_network
      - public_network

  frontend:
    build:
      context: ./app/angular-frontend
    container_name: acoi_angular_frontend
    ports:
      - "8088:80"
    depends_on:
      - backend
    networks:
      - public_network

volumes:
  acoi_mysql_data:

networks:
  internal_network:
    internal: true
  public_network:
